#ifndef DEMON_BUILDER_H
#define DEMON_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef DEMON_READER_H
#include "demon_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

#define __demon_InotifyEvent_formal_args , demon_InotifyEvent_enum_t v0
#define __demon_InotifyEvent_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, demon_InotifyEvent, demon_InotifyEvent_enum_t)

typedef flatbuffers_union_ref_t demon_Surveillance_union_ref_t;
typedef flatbuffers_union_vec_ref_t demon_Surveillance_union_vec_ref_t;
static demon_Surveillance_union_ref_t demon_Surveillance_clone(flatbuffers_builder_t *B, demon_Surveillance_union_t t);
typedef flatbuffers_union_ref_t demon_Event_union_ref_t;
typedef flatbuffers_union_vec_ref_t demon_Event_union_vec_ref_t;
static demon_Event_union_ref_t demon_Event_clone(flatbuffers_builder_t *B, demon_Event_union_t t);

static const flatbuffers_voffset_t __demon_Inotify_required[] = { 0 };
typedef flatbuffers_ref_t demon_Inotify_ref_t;
static demon_Inotify_ref_t demon_Inotify_clone(flatbuffers_builder_t *B, demon_Inotify_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_Inotify, 3)

static const flatbuffers_voffset_t __demon_TCPSocket_required[] = { 0 };
typedef flatbuffers_ref_t demon_TCPSocket_ref_t;
static demon_TCPSocket_ref_t demon_TCPSocket_clone(flatbuffers_builder_t *B, demon_TCPSocket_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_TCPSocket, 1)

static const flatbuffers_voffset_t __demon_SurveillanceEvent_required[] = { 0 };
typedef flatbuffers_ref_t demon_SurveillanceEvent_ref_t;
static demon_SurveillanceEvent_ref_t demon_SurveillanceEvent_clone(flatbuffers_builder_t *B, demon_SurveillanceEvent_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_SurveillanceEvent, 2)

static const flatbuffers_voffset_t __demon_RunCommand_required[] = { 0 };
typedef flatbuffers_ref_t demon_RunCommand_ref_t;
static demon_RunCommand_ref_t demon_RunCommand_clone(flatbuffers_builder_t *B, demon_RunCommand_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_RunCommand, 6)

static const flatbuffers_voffset_t __demon_KillProcess_required[] = { 0 };
typedef flatbuffers_ref_t demon_KillProcess_ref_t;
static demon_KillProcess_ref_t demon_KillProcess_clone(flatbuffers_builder_t *B, demon_KillProcess_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_KillProcess, 1)

static const flatbuffers_voffset_t __demon_ProcessLaunched_required[] = { 0 };
typedef flatbuffers_ref_t demon_ProcessLaunched_ref_t;
static demon_ProcessLaunched_ref_t demon_ProcessLaunched_clone(flatbuffers_builder_t *B, demon_ProcessLaunched_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_ProcessLaunched, 1)

static const flatbuffers_voffset_t __demon_ChildCreationError_required[] = { 0 };
typedef flatbuffers_ref_t demon_ChildCreationError_ref_t;
static demon_ChildCreationError_ref_t demon_ChildCreationError_clone(flatbuffers_builder_t *B, demon_ChildCreationError_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_ChildCreationError, 1)

static const flatbuffers_voffset_t __demon_ProcessTerminated_required[] = { 0 };
typedef flatbuffers_ref_t demon_ProcessTerminated_ref_t;
static demon_ProcessTerminated_ref_t demon_ProcessTerminated_clone(flatbuffers_builder_t *B, demon_ProcessTerminated_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_ProcessTerminated, 2)

static const flatbuffers_voffset_t __demon_TCPSocketListening_required[] = { 0 };
typedef flatbuffers_ref_t demon_TCPSocketListening_ref_t;
static demon_TCPSocketListening_ref_t demon_TCPSocketListening_clone(flatbuffers_builder_t *B, demon_TCPSocketListening_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_TCPSocketListening, 1)

static const flatbuffers_voffset_t __demon_InotifyPathUpdated_required[] = { 0 };
typedef flatbuffers_ref_t demon_InotifyPathUpdated_ref_t;
static demon_InotifyPathUpdated_ref_t demon_InotifyPathUpdated_clone(flatbuffers_builder_t *B, demon_InotifyPathUpdated_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_InotifyPathUpdated, 3)

static const flatbuffers_voffset_t __demon_EstablishTCPConnection_required[] = { 0 };
typedef flatbuffers_ref_t demon_EstablishTCPConnection_ref_t;
static demon_EstablishTCPConnection_ref_t demon_EstablishTCPConnection_clone(flatbuffers_builder_t *B, demon_EstablishTCPConnection_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_EstablishTCPConnection, 1)

static const flatbuffers_voffset_t __demon_EstablishUnixConnection_required[] = { 0 };
typedef flatbuffers_ref_t demon_EstablishUnixConnection_ref_t;
static demon_EstablishUnixConnection_ref_t demon_EstablishUnixConnection_clone(flatbuffers_builder_t *B, demon_EstablishUnixConnection_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_EstablishUnixConnection, 1)

static const flatbuffers_voffset_t __demon_Message_required[] = { 0 };
typedef flatbuffers_ref_t demon_Message_ref_t;
static demon_Message_ref_t demon_Message_clone(flatbuffers_builder_t *B, demon_Message_table_t t);
__flatbuffers_build_table(flatbuffers_, demon_Message, 2)

#define __demon_Inotify_formal_args , flatbuffers_string_ref_t v0, demon_InotifyEvent_vec_ref_t v1, uint32_t v2
#define __demon_Inotify_call_args , v0, v1, v2
static inline demon_Inotify_ref_t demon_Inotify_create(flatbuffers_builder_t *B __demon_Inotify_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_Inotify, demon_Inotify_file_identifier, demon_Inotify_type_identifier)

#define __demon_TCPSocket_formal_args , uint8_t v0
#define __demon_TCPSocket_call_args , v0
static inline demon_TCPSocket_ref_t demon_TCPSocket_create(flatbuffers_builder_t *B __demon_TCPSocket_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_TCPSocket, demon_TCPSocket_file_identifier, demon_TCPSocket_type_identifier)

#define __demon_SurveillanceEvent_formal_args , demon_Surveillance_union_ref_t v1
#define __demon_SurveillanceEvent_call_args , v1
static inline demon_SurveillanceEvent_ref_t demon_SurveillanceEvent_create(flatbuffers_builder_t *B __demon_SurveillanceEvent_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_SurveillanceEvent, demon_SurveillanceEvent_file_identifier, demon_SurveillanceEvent_type_identifier)

#define __demon_RunCommand_formal_args ,\
  flatbuffers_string_ref_t v0, flatbuffers_string_vec_ref_t v1, flatbuffers_string_vec_ref_t v2, uint32_t v3, uint32_t v4, demon_SurveillanceEvent_vec_ref_t v5
#define __demon_RunCommand_call_args ,\
  v0, v1, v2, v3, v4, v5
static inline demon_RunCommand_ref_t demon_RunCommand_create(flatbuffers_builder_t *B __demon_RunCommand_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_RunCommand, demon_RunCommand_file_identifier, demon_RunCommand_type_identifier)

#define __demon_KillProcess_formal_args , int32_t v0
#define __demon_KillProcess_call_args , v0
static inline demon_KillProcess_ref_t demon_KillProcess_create(flatbuffers_builder_t *B __demon_KillProcess_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_KillProcess, demon_KillProcess_file_identifier, demon_KillProcess_type_identifier)

#define __demon_ProcessLaunched_formal_args , int32_t v0
#define __demon_ProcessLaunched_call_args , v0
static inline demon_ProcessLaunched_ref_t demon_ProcessLaunched_create(flatbuffers_builder_t *B __demon_ProcessLaunched_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_ProcessLaunched, demon_ProcessLaunched_file_identifier, demon_ProcessLaunched_type_identifier)

#define __demon_ChildCreationError_formal_args , uint32_t v0
#define __demon_ChildCreationError_call_args , v0
static inline demon_ChildCreationError_ref_t demon_ChildCreationError_create(flatbuffers_builder_t *B __demon_ChildCreationError_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_ChildCreationError, demon_ChildCreationError_file_identifier, demon_ChildCreationError_type_identifier)

#define __demon_ProcessTerminated_formal_args , int32_t v0, uint32_t v1
#define __demon_ProcessTerminated_call_args , v0, v1
static inline demon_ProcessTerminated_ref_t demon_ProcessTerminated_create(flatbuffers_builder_t *B __demon_ProcessTerminated_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_ProcessTerminated, demon_ProcessTerminated_file_identifier, demon_ProcessTerminated_type_identifier)

#define __demon_TCPSocketListening_formal_args , uint16_t v0
#define __demon_TCPSocketListening_call_args , v0
static inline demon_TCPSocketListening_ref_t demon_TCPSocketListening_create(flatbuffers_builder_t *B __demon_TCPSocketListening_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_TCPSocketListening, demon_TCPSocketListening_file_identifier, demon_TCPSocketListening_type_identifier)

#define __demon_InotifyPathUpdated_formal_args , flatbuffers_string_ref_t v0, demon_InotifyEvent_vec_ref_t v1, uint32_t v2
#define __demon_InotifyPathUpdated_call_args , v0, v1, v2
static inline demon_InotifyPathUpdated_ref_t demon_InotifyPathUpdated_create(flatbuffers_builder_t *B __demon_InotifyPathUpdated_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_InotifyPathUpdated, demon_InotifyPathUpdated_file_identifier, demon_InotifyPathUpdated_type_identifier)

#define __demon_EstablishTCPConnection_formal_args , uint8_t v0
#define __demon_EstablishTCPConnection_call_args , v0
static inline demon_EstablishTCPConnection_ref_t demon_EstablishTCPConnection_create(flatbuffers_builder_t *B __demon_EstablishTCPConnection_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_EstablishTCPConnection, demon_EstablishTCPConnection_file_identifier, demon_EstablishTCPConnection_type_identifier)

#define __demon_EstablishUnixConnection_formal_args , flatbuffers_string_ref_t v0
#define __demon_EstablishUnixConnection_call_args , v0
static inline demon_EstablishUnixConnection_ref_t demon_EstablishUnixConnection_create(flatbuffers_builder_t *B __demon_EstablishUnixConnection_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_EstablishUnixConnection, demon_EstablishUnixConnection_file_identifier, demon_EstablishUnixConnection_type_identifier)

#define __demon_Message_formal_args , demon_Event_union_ref_t v1
#define __demon_Message_call_args , v1
static inline demon_Message_ref_t demon_Message_create(flatbuffers_builder_t *B __demon_Message_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, demon_Message, demon_Message_file_identifier, demon_Message_type_identifier)

static inline demon_Surveillance_union_ref_t demon_Surveillance_as_NONE(void)
{ demon_Surveillance_union_ref_t uref; uref.type = demon_Surveillance_NONE; uref.value = 0; return uref; }
static inline demon_Surveillance_union_ref_t demon_Surveillance_as_Inotify(demon_Inotify_ref_t ref)
{ demon_Surveillance_union_ref_t uref; uref.type = demon_Surveillance_Inotify; uref.value = ref; return uref; }
static inline demon_Surveillance_union_ref_t demon_Surveillance_as_TCPSocket(demon_TCPSocket_ref_t ref)
{ demon_Surveillance_union_ref_t uref; uref.type = demon_Surveillance_TCPSocket; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, demon_Surveillance)

static demon_Surveillance_union_ref_t demon_Surveillance_clone(flatbuffers_builder_t *B, demon_Surveillance_union_t u)
{
    switch (u.type) {
    case 1: return demon_Surveillance_as_Inotify(demon_Inotify_clone(B, (demon_Inotify_table_t)u.value));
    case 2: return demon_Surveillance_as_TCPSocket(demon_TCPSocket_clone(B, (demon_TCPSocket_table_t)u.value));
    default: return demon_Surveillance_as_NONE();
    }
}

static inline demon_Event_union_ref_t demon_Event_as_NONE(void)
{ demon_Event_union_ref_t uref; uref.type = demon_Event_NONE; uref.value = 0; return uref; }
static inline demon_Event_union_ref_t demon_Event_as_RunCommand(demon_RunCommand_ref_t ref)
{ demon_Event_union_ref_t uref; uref.type = demon_Event_RunCommand; uref.value = ref; return uref; }
static inline demon_Event_union_ref_t demon_Event_as_KillProcess(demon_KillProcess_ref_t ref)
{ demon_Event_union_ref_t uref; uref.type = demon_Event_KillProcess; uref.value = ref; return uref; }
static inline demon_Event_union_ref_t demon_Event_as_EstablishTCPConnection(demon_EstablishTCPConnection_ref_t ref)
{ demon_Event_union_ref_t uref; uref.type = demon_Event_EstablishTCPConnection; uref.value = ref; return uref; }
static inline demon_Event_union_ref_t demon_Event_as_EstablishUnixConnection(demon_EstablishUnixConnection_ref_t ref)
{ demon_Event_union_ref_t uref; uref.type = demon_Event_EstablishUnixConnection; uref.value = ref; return uref; }
static inline demon_Event_union_ref_t demon_Event_as_ProcessLaunched(demon_ProcessLaunched_ref_t ref)
{ demon_Event_union_ref_t uref; uref.type = demon_Event_ProcessLaunched; uref.value = ref; return uref; }
static inline demon_Event_union_ref_t demon_Event_as_ChildCreationError(demon_ChildCreationError_ref_t ref)
{ demon_Event_union_ref_t uref; uref.type = demon_Event_ChildCreationError; uref.value = ref; return uref; }
static inline demon_Event_union_ref_t demon_Event_as_ProcessTerminated(demon_ProcessTerminated_ref_t ref)
{ demon_Event_union_ref_t uref; uref.type = demon_Event_ProcessTerminated; uref.value = ref; return uref; }
static inline demon_Event_union_ref_t demon_Event_as_TCPSocketListening(demon_TCPSocketListening_ref_t ref)
{ demon_Event_union_ref_t uref; uref.type = demon_Event_TCPSocketListening; uref.value = ref; return uref; }
static inline demon_Event_union_ref_t demon_Event_as_InotifyPathUpdated(demon_InotifyPathUpdated_ref_t ref)
{ demon_Event_union_ref_t uref; uref.type = demon_Event_InotifyPathUpdated; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, demon_Event)

static demon_Event_union_ref_t demon_Event_clone(flatbuffers_builder_t *B, demon_Event_union_t u)
{
    switch (u.type) {
    case 1: return demon_Event_as_RunCommand(demon_RunCommand_clone(B, (demon_RunCommand_table_t)u.value));
    case 2: return demon_Event_as_KillProcess(demon_KillProcess_clone(B, (demon_KillProcess_table_t)u.value));
    case 3: return demon_Event_as_EstablishTCPConnection(demon_EstablishTCPConnection_clone(B, (demon_EstablishTCPConnection_table_t)u.value));
    case 4: return demon_Event_as_EstablishUnixConnection(demon_EstablishUnixConnection_clone(B, (demon_EstablishUnixConnection_table_t)u.value));
    case 5: return demon_Event_as_ProcessLaunched(demon_ProcessLaunched_clone(B, (demon_ProcessLaunched_table_t)u.value));
    case 6: return demon_Event_as_ChildCreationError(demon_ChildCreationError_clone(B, (demon_ChildCreationError_table_t)u.value));
    case 7: return demon_Event_as_ProcessTerminated(demon_ProcessTerminated_clone(B, (demon_ProcessTerminated_table_t)u.value));
    case 8: return demon_Event_as_TCPSocketListening(demon_TCPSocketListening_clone(B, (demon_TCPSocketListening_table_t)u.value));
    case 9: return demon_Event_as_InotifyPathUpdated(demon_InotifyPathUpdated_clone(B, (demon_InotifyPathUpdated_table_t)u.value));
    default: return demon_Event_as_NONE();
    }
}

__flatbuffers_build_string_field(0, flatbuffers_, demon_Inotify_root_paths, demon_Inotify)
__flatbuffers_build_vector_field(1, flatbuffers_, demon_Inotify_trigger_events, demon_InotifyEvent, demon_InotifyEvent_enum_t, demon_Inotify)
__flatbuffers_build_scalar_field(2, flatbuffers_, demon_Inotify_size, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), demon_Inotify)

static inline demon_Inotify_ref_t demon_Inotify_create(flatbuffers_builder_t *B __demon_Inotify_formal_args)
{
    if (demon_Inotify_start(B)
        || demon_Inotify_root_paths_add(B, v0)
        || demon_Inotify_trigger_events_add(B, v1)
        || demon_Inotify_size_add(B, v2)) {
        return 0;
    }
    return demon_Inotify_end(B);
}

static demon_Inotify_ref_t demon_Inotify_clone(flatbuffers_builder_t *B, demon_Inotify_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_Inotify_start(B)
        || demon_Inotify_root_paths_pick(B, t)
        || demon_Inotify_trigger_events_pick(B, t)
        || demon_Inotify_size_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_Inotify_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, demon_TCPSocket_destport, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), demon_TCPSocket)

static inline demon_TCPSocket_ref_t demon_TCPSocket_create(flatbuffers_builder_t *B __demon_TCPSocket_formal_args)
{
    if (demon_TCPSocket_start(B)
        || demon_TCPSocket_destport_add(B, v0)) {
        return 0;
    }
    return demon_TCPSocket_end(B);
}

static demon_TCPSocket_ref_t demon_TCPSocket_clone(flatbuffers_builder_t *B, demon_TCPSocket_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_TCPSocket_start(B)
        || demon_TCPSocket_destport_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_TCPSocket_end(B));
}

__flatbuffers_build_union_field(1, flatbuffers_, demon_SurveillanceEvent_event, demon_Surveillance, demon_SurveillanceEvent)
__flatbuffers_build_union_table_value_field(flatbuffers_, demon_SurveillanceEvent_event, demon_Surveillance, Inotify, demon_Inotify)
__flatbuffers_build_union_table_value_field(flatbuffers_, demon_SurveillanceEvent_event, demon_Surveillance, TCPSocket, demon_TCPSocket)

static inline demon_SurveillanceEvent_ref_t demon_SurveillanceEvent_create(flatbuffers_builder_t *B __demon_SurveillanceEvent_formal_args)
{
    if (demon_SurveillanceEvent_start(B)
        || demon_SurveillanceEvent_event_add_value(B, v1)
        || demon_SurveillanceEvent_event_add_type(B, v1.type)) {
        return 0;
    }
    return demon_SurveillanceEvent_end(B);
}

static demon_SurveillanceEvent_ref_t demon_SurveillanceEvent_clone(flatbuffers_builder_t *B, demon_SurveillanceEvent_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_SurveillanceEvent_start(B)
        || demon_SurveillanceEvent_event_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_SurveillanceEvent_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, demon_RunCommand_path, demon_RunCommand)
__flatbuffers_build_string_vector_field(1, flatbuffers_, demon_RunCommand_args, demon_RunCommand)
__flatbuffers_build_string_vector_field(2, flatbuffers_, demon_RunCommand_envp, demon_RunCommand)
__flatbuffers_build_scalar_field(3, flatbuffers_, demon_RunCommand_flags, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), demon_RunCommand)
__flatbuffers_build_scalar_field(4, flatbuffers_, demon_RunCommand_stack_size, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), demon_RunCommand)
__flatbuffers_build_table_vector_field(5, flatbuffers_, demon_RunCommand_to_watch, demon_SurveillanceEvent, demon_RunCommand)

static inline demon_RunCommand_ref_t demon_RunCommand_create(flatbuffers_builder_t *B __demon_RunCommand_formal_args)
{
    if (demon_RunCommand_start(B)
        || demon_RunCommand_path_add(B, v0)
        || demon_RunCommand_args_add(B, v1)
        || demon_RunCommand_envp_add(B, v2)
        || demon_RunCommand_flags_add(B, v3)
        || demon_RunCommand_stack_size_add(B, v4)
        || demon_RunCommand_to_watch_add(B, v5)) {
        return 0;
    }
    return demon_RunCommand_end(B);
}

static demon_RunCommand_ref_t demon_RunCommand_clone(flatbuffers_builder_t *B, demon_RunCommand_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_RunCommand_start(B)
        || demon_RunCommand_path_pick(B, t)
        || demon_RunCommand_args_pick(B, t)
        || demon_RunCommand_envp_pick(B, t)
        || demon_RunCommand_flags_pick(B, t)
        || demon_RunCommand_stack_size_pick(B, t)
        || demon_RunCommand_to_watch_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_RunCommand_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, demon_KillProcess_pid, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), demon_KillProcess)

static inline demon_KillProcess_ref_t demon_KillProcess_create(flatbuffers_builder_t *B __demon_KillProcess_formal_args)
{
    if (demon_KillProcess_start(B)
        || demon_KillProcess_pid_add(B, v0)) {
        return 0;
    }
    return demon_KillProcess_end(B);
}

static demon_KillProcess_ref_t demon_KillProcess_clone(flatbuffers_builder_t *B, demon_KillProcess_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_KillProcess_start(B)
        || demon_KillProcess_pid_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_KillProcess_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, demon_ProcessLaunched_pid, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), demon_ProcessLaunched)

static inline demon_ProcessLaunched_ref_t demon_ProcessLaunched_create(flatbuffers_builder_t *B __demon_ProcessLaunched_formal_args)
{
    if (demon_ProcessLaunched_start(B)
        || demon_ProcessLaunched_pid_add(B, v0)) {
        return 0;
    }
    return demon_ProcessLaunched_end(B);
}

static demon_ProcessLaunched_ref_t demon_ProcessLaunched_clone(flatbuffers_builder_t *B, demon_ProcessLaunched_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_ProcessLaunched_start(B)
        || demon_ProcessLaunched_pid_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_ProcessLaunched_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, demon_ChildCreationError_error_code, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), demon_ChildCreationError)

static inline demon_ChildCreationError_ref_t demon_ChildCreationError_create(flatbuffers_builder_t *B __demon_ChildCreationError_formal_args)
{
    if (demon_ChildCreationError_start(B)
        || demon_ChildCreationError_error_code_add(B, v0)) {
        return 0;
    }
    return demon_ChildCreationError_end(B);
}

static demon_ChildCreationError_ref_t demon_ChildCreationError_clone(flatbuffers_builder_t *B, demon_ChildCreationError_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_ChildCreationError_start(B)
        || demon_ChildCreationError_error_code_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_ChildCreationError_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, demon_ProcessTerminated_pid, flatbuffers_int32, int32_t, 4, 4, INT32_C(0), demon_ProcessTerminated)
__flatbuffers_build_scalar_field(1, flatbuffers_, demon_ProcessTerminated_error_code, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), demon_ProcessTerminated)

static inline demon_ProcessTerminated_ref_t demon_ProcessTerminated_create(flatbuffers_builder_t *B __demon_ProcessTerminated_formal_args)
{
    if (demon_ProcessTerminated_start(B)
        || demon_ProcessTerminated_pid_add(B, v0)
        || demon_ProcessTerminated_error_code_add(B, v1)) {
        return 0;
    }
    return demon_ProcessTerminated_end(B);
}

static demon_ProcessTerminated_ref_t demon_ProcessTerminated_clone(flatbuffers_builder_t *B, demon_ProcessTerminated_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_ProcessTerminated_start(B)
        || demon_ProcessTerminated_pid_pick(B, t)
        || demon_ProcessTerminated_error_code_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_ProcessTerminated_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, demon_TCPSocketListening_port, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), demon_TCPSocketListening)

static inline demon_TCPSocketListening_ref_t demon_TCPSocketListening_create(flatbuffers_builder_t *B __demon_TCPSocketListening_formal_args)
{
    if (demon_TCPSocketListening_start(B)
        || demon_TCPSocketListening_port_add(B, v0)) {
        return 0;
    }
    return demon_TCPSocketListening_end(B);
}

static demon_TCPSocketListening_ref_t demon_TCPSocketListening_clone(flatbuffers_builder_t *B, demon_TCPSocketListening_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_TCPSocketListening_start(B)
        || demon_TCPSocketListening_port_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_TCPSocketListening_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, demon_InotifyPathUpdated_path, demon_InotifyPathUpdated)
__flatbuffers_build_vector_field(1, flatbuffers_, demon_InotifyPathUpdated_trigger_events, demon_InotifyEvent, demon_InotifyEvent_enum_t, demon_InotifyPathUpdated)
__flatbuffers_build_scalar_field(2, flatbuffers_, demon_InotifyPathUpdated_size, flatbuffers_uint32, uint32_t, 4, 4, UINT32_C(0), demon_InotifyPathUpdated)

static inline demon_InotifyPathUpdated_ref_t demon_InotifyPathUpdated_create(flatbuffers_builder_t *B __demon_InotifyPathUpdated_formal_args)
{
    if (demon_InotifyPathUpdated_start(B)
        || demon_InotifyPathUpdated_path_add(B, v0)
        || demon_InotifyPathUpdated_trigger_events_add(B, v1)
        || demon_InotifyPathUpdated_size_add(B, v2)) {
        return 0;
    }
    return demon_InotifyPathUpdated_end(B);
}

static demon_InotifyPathUpdated_ref_t demon_InotifyPathUpdated_clone(flatbuffers_builder_t *B, demon_InotifyPathUpdated_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_InotifyPathUpdated_start(B)
        || demon_InotifyPathUpdated_path_pick(B, t)
        || demon_InotifyPathUpdated_trigger_events_pick(B, t)
        || demon_InotifyPathUpdated_size_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_InotifyPathUpdated_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, demon_EstablishTCPConnection_destport, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), demon_EstablishTCPConnection)

static inline demon_EstablishTCPConnection_ref_t demon_EstablishTCPConnection_create(flatbuffers_builder_t *B __demon_EstablishTCPConnection_formal_args)
{
    if (demon_EstablishTCPConnection_start(B)
        || demon_EstablishTCPConnection_destport_add(B, v0)) {
        return 0;
    }
    return demon_EstablishTCPConnection_end(B);
}

static demon_EstablishTCPConnection_ref_t demon_EstablishTCPConnection_clone(flatbuffers_builder_t *B, demon_EstablishTCPConnection_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_EstablishTCPConnection_start(B)
        || demon_EstablishTCPConnection_destport_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_EstablishTCPConnection_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, demon_EstablishUnixConnection_path, demon_EstablishUnixConnection)

static inline demon_EstablishUnixConnection_ref_t demon_EstablishUnixConnection_create(flatbuffers_builder_t *B __demon_EstablishUnixConnection_formal_args)
{
    if (demon_EstablishUnixConnection_start(B)
        || demon_EstablishUnixConnection_path_add(B, v0)) {
        return 0;
    }
    return demon_EstablishUnixConnection_end(B);
}

static demon_EstablishUnixConnection_ref_t demon_EstablishUnixConnection_clone(flatbuffers_builder_t *B, demon_EstablishUnixConnection_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_EstablishUnixConnection_start(B)
        || demon_EstablishUnixConnection_path_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_EstablishUnixConnection_end(B));
}

__flatbuffers_build_union_field(1, flatbuffers_, demon_Message_events, demon_Event, demon_Message)
__flatbuffers_build_union_table_value_field(flatbuffers_, demon_Message_events, demon_Event, RunCommand, demon_RunCommand)
__flatbuffers_build_union_table_value_field(flatbuffers_, demon_Message_events, demon_Event, KillProcess, demon_KillProcess)
__flatbuffers_build_union_table_value_field(flatbuffers_, demon_Message_events, demon_Event, EstablishTCPConnection, demon_EstablishTCPConnection)
__flatbuffers_build_union_table_value_field(flatbuffers_, demon_Message_events, demon_Event, EstablishUnixConnection, demon_EstablishUnixConnection)
__flatbuffers_build_union_table_value_field(flatbuffers_, demon_Message_events, demon_Event, ProcessLaunched, demon_ProcessLaunched)
__flatbuffers_build_union_table_value_field(flatbuffers_, demon_Message_events, demon_Event, ChildCreationError, demon_ChildCreationError)
__flatbuffers_build_union_table_value_field(flatbuffers_, demon_Message_events, demon_Event, ProcessTerminated, demon_ProcessTerminated)
__flatbuffers_build_union_table_value_field(flatbuffers_, demon_Message_events, demon_Event, TCPSocketListening, demon_TCPSocketListening)
__flatbuffers_build_union_table_value_field(flatbuffers_, demon_Message_events, demon_Event, InotifyPathUpdated, demon_InotifyPathUpdated)

static inline demon_Message_ref_t demon_Message_create(flatbuffers_builder_t *B __demon_Message_formal_args)
{
    if (demon_Message_start(B)
        || demon_Message_events_add_value(B, v1)
        || demon_Message_events_add_type(B, v1.type)) {
        return 0;
    }
    return demon_Message_end(B);
}

static demon_Message_ref_t demon_Message_clone(flatbuffers_builder_t *B, demon_Message_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (demon_Message_start(B)
        || demon_Message_events_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, demon_Message_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* DEMON_BUILDER_H */
