#ifndef DEMON_READER_H
#define DEMON_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct demon_Inotify_table *demon_Inotify_table_t;
typedef struct demon_Inotify_table *demon_Inotify_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_Inotify_vec_t;
typedef flatbuffers_uoffset_t *demon_Inotify_mutable_vec_t;
typedef const struct demon_TCPSocket_table *demon_TCPSocket_table_t;
typedef struct demon_TCPSocket_table *demon_TCPSocket_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_TCPSocket_vec_t;
typedef flatbuffers_uoffset_t *demon_TCPSocket_mutable_vec_t;
typedef const struct demon_SurveillanceEvent_table *demon_SurveillanceEvent_table_t;
typedef struct demon_SurveillanceEvent_table *demon_SurveillanceEvent_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_SurveillanceEvent_vec_t;
typedef flatbuffers_uoffset_t *demon_SurveillanceEvent_mutable_vec_t;
typedef const struct demon_RunCommand_table *demon_RunCommand_table_t;
typedef struct demon_RunCommand_table *demon_RunCommand_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_RunCommand_vec_t;
typedef flatbuffers_uoffset_t *demon_RunCommand_mutable_vec_t;
typedef const struct demon_KillProcess_table *demon_KillProcess_table_t;
typedef struct demon_KillProcess_table *demon_KillProcess_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_KillProcess_vec_t;
typedef flatbuffers_uoffset_t *demon_KillProcess_mutable_vec_t;
typedef const struct demon_ProcessLaunched_table *demon_ProcessLaunched_table_t;
typedef struct demon_ProcessLaunched_table *demon_ProcessLaunched_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_ProcessLaunched_vec_t;
typedef flatbuffers_uoffset_t *demon_ProcessLaunched_mutable_vec_t;
typedef const struct demon_ChildCreationError_table *demon_ChildCreationError_table_t;
typedef struct demon_ChildCreationError_table *demon_ChildCreationError_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_ChildCreationError_vec_t;
typedef flatbuffers_uoffset_t *demon_ChildCreationError_mutable_vec_t;
typedef const struct demon_ProcessTerminated_table *demon_ProcessTerminated_table_t;
typedef struct demon_ProcessTerminated_table *demon_ProcessTerminated_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_ProcessTerminated_vec_t;
typedef flatbuffers_uoffset_t *demon_ProcessTerminated_mutable_vec_t;
typedef const struct demon_TCPSocketListening_table *demon_TCPSocketListening_table_t;
typedef struct demon_TCPSocketListening_table *demon_TCPSocketListening_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_TCPSocketListening_vec_t;
typedef flatbuffers_uoffset_t *demon_TCPSocketListening_mutable_vec_t;
typedef const struct demon_InotifyPathUpdated_table *demon_InotifyPathUpdated_table_t;
typedef struct demon_InotifyPathUpdated_table *demon_InotifyPathUpdated_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_InotifyPathUpdated_vec_t;
typedef flatbuffers_uoffset_t *demon_InotifyPathUpdated_mutable_vec_t;
typedef const struct demon_EstablishTCPConnection_table *demon_EstablishTCPConnection_table_t;
typedef struct demon_EstablishTCPConnection_table *demon_EstablishTCPConnection_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_EstablishTCPConnection_vec_t;
typedef flatbuffers_uoffset_t *demon_EstablishTCPConnection_mutable_vec_t;
typedef const struct demon_EstablishUnixConnection_table *demon_EstablishUnixConnection_table_t;
typedef struct demon_EstablishUnixConnection_table *demon_EstablishUnixConnection_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_EstablishUnixConnection_vec_t;
typedef flatbuffers_uoffset_t *demon_EstablishUnixConnection_mutable_vec_t;
typedef const struct demon_Message_table *demon_Message_table_t;
typedef struct demon_Message_table *demon_Message_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_Message_vec_t;
typedef flatbuffers_uoffset_t *demon_Message_mutable_vec_t;
#ifndef demon_Inotify_file_identifier
#define demon_Inotify_file_identifier 0
#endif
/* deprecated, use demon_Inotify_file_identifier */
#ifndef demon_Inotify_identifier
#define demon_Inotify_identifier 0
#endif
#define demon_Inotify_type_hash ((flatbuffers_thash_t)0x574dbae8)
#define demon_Inotify_type_identifier "\xe8\xba\x4d\x57"
#ifndef demon_Inotify_file_extension
#define demon_Inotify_file_extension "bin"
#endif
#ifndef demon_TCPSocket_file_identifier
#define demon_TCPSocket_file_identifier 0
#endif
/* deprecated, use demon_TCPSocket_file_identifier */
#ifndef demon_TCPSocket_identifier
#define demon_TCPSocket_identifier 0
#endif
#define demon_TCPSocket_type_hash ((flatbuffers_thash_t)0x2a72ed68)
#define demon_TCPSocket_type_identifier "\x68\xed\x72\x2a"
#ifndef demon_TCPSocket_file_extension
#define demon_TCPSocket_file_extension "bin"
#endif
#ifndef demon_SurveillanceEvent_file_identifier
#define demon_SurveillanceEvent_file_identifier 0
#endif
/* deprecated, use demon_SurveillanceEvent_file_identifier */
#ifndef demon_SurveillanceEvent_identifier
#define demon_SurveillanceEvent_identifier 0
#endif
#define demon_SurveillanceEvent_type_hash ((flatbuffers_thash_t)0x58f8be05)
#define demon_SurveillanceEvent_type_identifier "\x05\xbe\xf8\x58"
#ifndef demon_SurveillanceEvent_file_extension
#define demon_SurveillanceEvent_file_extension "bin"
#endif
#ifndef demon_RunCommand_file_identifier
#define demon_RunCommand_file_identifier 0
#endif
/* deprecated, use demon_RunCommand_file_identifier */
#ifndef demon_RunCommand_identifier
#define demon_RunCommand_identifier 0
#endif
#define demon_RunCommand_type_hash ((flatbuffers_thash_t)0x84d66400)
#define demon_RunCommand_type_identifier "\x00\x64\xd6\x84"
#ifndef demon_RunCommand_file_extension
#define demon_RunCommand_file_extension "bin"
#endif
#ifndef demon_KillProcess_file_identifier
#define demon_KillProcess_file_identifier 0
#endif
/* deprecated, use demon_KillProcess_file_identifier */
#ifndef demon_KillProcess_identifier
#define demon_KillProcess_identifier 0
#endif
#define demon_KillProcess_type_hash ((flatbuffers_thash_t)0x157dd3fb)
#define demon_KillProcess_type_identifier "\xfb\xd3\x7d\x15"
#ifndef demon_KillProcess_file_extension
#define demon_KillProcess_file_extension "bin"
#endif
#ifndef demon_ProcessLaunched_file_identifier
#define demon_ProcessLaunched_file_identifier 0
#endif
/* deprecated, use demon_ProcessLaunched_file_identifier */
#ifndef demon_ProcessLaunched_identifier
#define demon_ProcessLaunched_identifier 0
#endif
#define demon_ProcessLaunched_type_hash ((flatbuffers_thash_t)0x23616be1)
#define demon_ProcessLaunched_type_identifier "\xe1\x6b\x61\x23"
#ifndef demon_ProcessLaunched_file_extension
#define demon_ProcessLaunched_file_extension "bin"
#endif
#ifndef demon_ChildCreationError_file_identifier
#define demon_ChildCreationError_file_identifier 0
#endif
/* deprecated, use demon_ChildCreationError_file_identifier */
#ifndef demon_ChildCreationError_identifier
#define demon_ChildCreationError_identifier 0
#endif
#define demon_ChildCreationError_type_hash ((flatbuffers_thash_t)0x51bd0bb5)
#define demon_ChildCreationError_type_identifier "\xb5\x0b\xbd\x51"
#ifndef demon_ChildCreationError_file_extension
#define demon_ChildCreationError_file_extension "bin"
#endif
#ifndef demon_ProcessTerminated_file_identifier
#define demon_ProcessTerminated_file_identifier 0
#endif
/* deprecated, use demon_ProcessTerminated_file_identifier */
#ifndef demon_ProcessTerminated_identifier
#define demon_ProcessTerminated_identifier 0
#endif
#define demon_ProcessTerminated_type_hash ((flatbuffers_thash_t)0x88bcfd1a)
#define demon_ProcessTerminated_type_identifier "\x1a\xfd\xbc\x88"
#ifndef demon_ProcessTerminated_file_extension
#define demon_ProcessTerminated_file_extension "bin"
#endif
#ifndef demon_TCPSocketListening_file_identifier
#define demon_TCPSocketListening_file_identifier 0
#endif
/* deprecated, use demon_TCPSocketListening_file_identifier */
#ifndef demon_TCPSocketListening_identifier
#define demon_TCPSocketListening_identifier 0
#endif
#define demon_TCPSocketListening_type_hash ((flatbuffers_thash_t)0xdf7be345)
#define demon_TCPSocketListening_type_identifier "\x45\xe3\x7b\xdf"
#ifndef demon_TCPSocketListening_file_extension
#define demon_TCPSocketListening_file_extension "bin"
#endif
#ifndef demon_InotifyPathUpdated_file_identifier
#define demon_InotifyPathUpdated_file_identifier 0
#endif
/* deprecated, use demon_InotifyPathUpdated_file_identifier */
#ifndef demon_InotifyPathUpdated_identifier
#define demon_InotifyPathUpdated_identifier 0
#endif
#define demon_InotifyPathUpdated_type_hash ((flatbuffers_thash_t)0x6811089e)
#define demon_InotifyPathUpdated_type_identifier "\x9e\x08\x11\x68"
#ifndef demon_InotifyPathUpdated_file_extension
#define demon_InotifyPathUpdated_file_extension "bin"
#endif
#ifndef demon_EstablishTCPConnection_file_identifier
#define demon_EstablishTCPConnection_file_identifier 0
#endif
/* deprecated, use demon_EstablishTCPConnection_file_identifier */
#ifndef demon_EstablishTCPConnection_identifier
#define demon_EstablishTCPConnection_identifier 0
#endif
#define demon_EstablishTCPConnection_type_hash ((flatbuffers_thash_t)0x3942e144)
#define demon_EstablishTCPConnection_type_identifier "\x44\xe1\x42\x39"
#ifndef demon_EstablishTCPConnection_file_extension
#define demon_EstablishTCPConnection_file_extension "bin"
#endif
#ifndef demon_EstablishUnixConnection_file_identifier
#define demon_EstablishUnixConnection_file_identifier 0
#endif
/* deprecated, use demon_EstablishUnixConnection_file_identifier */
#ifndef demon_EstablishUnixConnection_identifier
#define demon_EstablishUnixConnection_identifier 0
#endif
#define demon_EstablishUnixConnection_type_hash ((flatbuffers_thash_t)0xfb756eff)
#define demon_EstablishUnixConnection_type_identifier "\xff\x6e\x75\xfb"
#ifndef demon_EstablishUnixConnection_file_extension
#define demon_EstablishUnixConnection_file_extension "bin"
#endif
#ifndef demon_Message_file_identifier
#define demon_Message_file_identifier 0
#endif
/* deprecated, use demon_Message_file_identifier */
#ifndef demon_Message_identifier
#define demon_Message_identifier 0
#endif
#define demon_Message_type_hash ((flatbuffers_thash_t)0x5a6e7ab9)
#define demon_Message_type_identifier "\xb9\x7a\x6e\x5a"
#ifndef demon_Message_file_extension
#define demon_Message_file_extension "bin"
#endif

typedef int8_t demon_InotifyEvent_enum_t;
__flatbuffers_define_integer_type(demon_InotifyEvent, demon_InotifyEvent_enum_t, 8)
#define demon_InotifyEvent_modification ((demon_InotifyEvent_enum_t)INT8_C(0))
#define demon_InotifyEvent_creation ((demon_InotifyEvent_enum_t)INT8_C(1))
#define demon_InotifyEvent_size ((demon_InotifyEvent_enum_t)INT8_C(2))
#define demon_InotifyEvent_deletion ((demon_InotifyEvent_enum_t)INT8_C(3))
#define demon_InotifyEvent_access ((demon_InotifyEvent_enum_t)INT8_C(4))

static inline const char *demon_InotifyEvent_name(demon_InotifyEvent_enum_t value)
{
    switch (value) {
    case demon_InotifyEvent_modification: return "modification";
    case demon_InotifyEvent_creation: return "creation";
    case demon_InotifyEvent_size: return "size";
    case demon_InotifyEvent_deletion: return "deletion";
    case demon_InotifyEvent_access: return "access";
    default: return "";
    }
}

static inline int demon_InotifyEvent_is_known_value(demon_InotifyEvent_enum_t value)
{
    switch (value) {
    case demon_InotifyEvent_modification: return 1;
    case demon_InotifyEvent_creation: return 1;
    case demon_InotifyEvent_size: return 1;
    case demon_InotifyEvent_deletion: return 1;
    case demon_InotifyEvent_access: return 1;
    default: return 0;
    }
}



struct demon_Inotify_table { uint8_t unused__; };

static inline size_t demon_Inotify_vec_len(demon_Inotify_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_Inotify_table_t demon_Inotify_vec_at(demon_Inotify_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_Inotify_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_Inotify)

__flatbuffers_define_string_field(0, demon_Inotify, root_paths, 0)
__flatbuffers_define_vector_field(1, demon_Inotify, trigger_events, demon_InotifyEvent_vec_t, 0)
__flatbuffers_define_scalar_field(2, demon_Inotify, size, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct demon_TCPSocket_table { uint8_t unused__; };

static inline size_t demon_TCPSocket_vec_len(demon_TCPSocket_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_TCPSocket_table_t demon_TCPSocket_vec_at(demon_TCPSocket_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_TCPSocket_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_TCPSocket)

__flatbuffers_define_scalar_field(0, demon_TCPSocket, destport, flatbuffers_uint8, uint8_t, UINT8_C(0))
typedef uint8_t demon_Surveillance_union_type_t;
__flatbuffers_define_integer_type(demon_Surveillance, demon_Surveillance_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, demon_Surveillance)
#define demon_Surveillance_NONE ((demon_Surveillance_union_type_t)UINT8_C(0))
#define demon_Surveillance_Inotify ((demon_Surveillance_union_type_t)UINT8_C(1))
#define demon_Surveillance_TCPSocket ((demon_Surveillance_union_type_t)UINT8_C(2))

static inline const char *demon_Surveillance_type_name(demon_Surveillance_union_type_t type)
{
    switch (type) {
    case demon_Surveillance_NONE: return "NONE";
    case demon_Surveillance_Inotify: return "Inotify";
    case demon_Surveillance_TCPSocket: return "TCPSocket";
    default: return "";
    }
}

static inline int demon_Surveillance_is_known_type(demon_Surveillance_union_type_t type)
{
    switch (type) {
    case demon_Surveillance_NONE: return 1;
    case demon_Surveillance_Inotify: return 1;
    case demon_Surveillance_TCPSocket: return 1;
    default: return 0;
    }
}


struct demon_SurveillanceEvent_table { uint8_t unused__; };

static inline size_t demon_SurveillanceEvent_vec_len(demon_SurveillanceEvent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_SurveillanceEvent_table_t demon_SurveillanceEvent_vec_at(demon_SurveillanceEvent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_SurveillanceEvent_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_SurveillanceEvent)

__flatbuffers_define_union_field(flatbuffers_, 1, demon_SurveillanceEvent, event, demon_Surveillance, 0)

struct demon_RunCommand_table { uint8_t unused__; };

static inline size_t demon_RunCommand_vec_len(demon_RunCommand_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_RunCommand_table_t demon_RunCommand_vec_at(demon_RunCommand_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_RunCommand_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_RunCommand)

__flatbuffers_define_string_field(0, demon_RunCommand, path, 0)
__flatbuffers_define_vector_field(1, demon_RunCommand, args, flatbuffers_string_vec_t, 0)
__flatbuffers_define_vector_field(2, demon_RunCommand, envp, flatbuffers_string_vec_t, 0)
__flatbuffers_define_scalar_field(3, demon_RunCommand, flags, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_scalar_field(4, demon_RunCommand, stack_size, flatbuffers_uint32, uint32_t, UINT32_C(0))
__flatbuffers_define_vector_field(5, demon_RunCommand, to_watch, demon_SurveillanceEvent_vec_t, 0)

struct demon_KillProcess_table { uint8_t unused__; };

static inline size_t demon_KillProcess_vec_len(demon_KillProcess_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_KillProcess_table_t demon_KillProcess_vec_at(demon_KillProcess_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_KillProcess_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_KillProcess)

__flatbuffers_define_scalar_field(0, demon_KillProcess, pid, flatbuffers_int32, int32_t, INT32_C(0))

struct demon_ProcessLaunched_table { uint8_t unused__; };

static inline size_t demon_ProcessLaunched_vec_len(demon_ProcessLaunched_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_ProcessLaunched_table_t demon_ProcessLaunched_vec_at(demon_ProcessLaunched_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_ProcessLaunched_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_ProcessLaunched)

__flatbuffers_define_scalar_field(0, demon_ProcessLaunched, pid, flatbuffers_int32, int32_t, INT32_C(0))

struct demon_ChildCreationError_table { uint8_t unused__; };

static inline size_t demon_ChildCreationError_vec_len(demon_ChildCreationError_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_ChildCreationError_table_t demon_ChildCreationError_vec_at(demon_ChildCreationError_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_ChildCreationError_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_ChildCreationError)

__flatbuffers_define_scalar_field(0, demon_ChildCreationError, errno, flatbuffers_uint32, uint32_t, UINT32_C(0))

struct demon_ProcessTerminated_table { uint8_t unused__; };

static inline size_t demon_ProcessTerminated_vec_len(demon_ProcessTerminated_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_ProcessTerminated_table_t demon_ProcessTerminated_vec_at(demon_ProcessTerminated_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_ProcessTerminated_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_ProcessTerminated)

__flatbuffers_define_scalar_field(0, demon_ProcessTerminated, pid, flatbuffers_int32, int32_t, INT32_C(0))

struct demon_TCPSocketListening_table { uint8_t unused__; };

static inline size_t demon_TCPSocketListening_vec_len(demon_TCPSocketListening_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_TCPSocketListening_table_t demon_TCPSocketListening_vec_at(demon_TCPSocketListening_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_TCPSocketListening_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_TCPSocketListening)

__flatbuffers_define_scalar_field(0, demon_TCPSocketListening, port, flatbuffers_uint16, uint16_t, UINT16_C(0))

struct demon_InotifyPathUpdated_table { uint8_t unused__; };

static inline size_t demon_InotifyPathUpdated_vec_len(demon_InotifyPathUpdated_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_InotifyPathUpdated_table_t demon_InotifyPathUpdated_vec_at(demon_InotifyPathUpdated_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_InotifyPathUpdated_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_InotifyPathUpdated)

__flatbuffers_define_string_field(0, demon_InotifyPathUpdated, path, 0)
__flatbuffers_define_vector_field(1, demon_InotifyPathUpdated, trigger_events, demon_InotifyEvent_vec_t, 0)

struct demon_EstablishTCPConnection_table { uint8_t unused__; };

static inline size_t demon_EstablishTCPConnection_vec_len(demon_EstablishTCPConnection_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_EstablishTCPConnection_table_t demon_EstablishTCPConnection_vec_at(demon_EstablishTCPConnection_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_EstablishTCPConnection_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_EstablishTCPConnection)

__flatbuffers_define_scalar_field(0, demon_EstablishTCPConnection, destport, flatbuffers_uint8, uint8_t, UINT8_C(0))

struct demon_EstablishUnixConnection_table { uint8_t unused__; };

static inline size_t demon_EstablishUnixConnection_vec_len(demon_EstablishUnixConnection_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_EstablishUnixConnection_table_t demon_EstablishUnixConnection_vec_at(demon_EstablishUnixConnection_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_EstablishUnixConnection_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_EstablishUnixConnection)

__flatbuffers_define_string_field(0, demon_EstablishUnixConnection, path, 0)
/** 
 *  Main message table
 *  */
typedef uint8_t demon_Event_union_type_t;
__flatbuffers_define_integer_type(demon_Event, demon_Event_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, demon_Event)
#define demon_Event_NONE ((demon_Event_union_type_t)UINT8_C(0))
#define demon_Event_RunCommand ((demon_Event_union_type_t)UINT8_C(1))
#define demon_Event_KillProcess ((demon_Event_union_type_t)UINT8_C(2))
#define demon_Event_EstablishTCPConnection ((demon_Event_union_type_t)UINT8_C(3))
#define demon_Event_EstablishUnixConnection ((demon_Event_union_type_t)UINT8_C(4))
#define demon_Event_ProcessLaunched ((demon_Event_union_type_t)UINT8_C(5))
#define demon_Event_ChildCreationError ((demon_Event_union_type_t)UINT8_C(6))
#define demon_Event_ProcessTerminated ((demon_Event_union_type_t)UINT8_C(7))
#define demon_Event_TCPSocketListening ((demon_Event_union_type_t)UINT8_C(8))
#define demon_Event_InotifyPathUpdated ((demon_Event_union_type_t)UINT8_C(9))

static inline const char *demon_Event_type_name(demon_Event_union_type_t type)
{
    switch (type) {
    case demon_Event_NONE: return "NONE";
    case demon_Event_RunCommand: return "RunCommand";
    case demon_Event_KillProcess: return "KillProcess";
    case demon_Event_EstablishTCPConnection: return "EstablishTCPConnection";
    case demon_Event_EstablishUnixConnection: return "EstablishUnixConnection";
    case demon_Event_ProcessLaunched: return "ProcessLaunched";
    case demon_Event_ChildCreationError: return "ChildCreationError";
    case demon_Event_ProcessTerminated: return "ProcessTerminated";
    case demon_Event_TCPSocketListening: return "TCPSocketListening";
    case demon_Event_InotifyPathUpdated: return "InotifyPathUpdated";
    default: return "";
    }
}

static inline int demon_Event_is_known_type(demon_Event_union_type_t type)
{
    switch (type) {
    case demon_Event_NONE: return 1;
    case demon_Event_RunCommand: return 1;
    case demon_Event_KillProcess: return 1;
    case demon_Event_EstablishTCPConnection: return 1;
    case demon_Event_EstablishUnixConnection: return 1;
    case demon_Event_ProcessLaunched: return 1;
    case demon_Event_ChildCreationError: return 1;
    case demon_Event_ProcessTerminated: return 1;
    case demon_Event_TCPSocketListening: return 1;
    case demon_Event_InotifyPathUpdated: return 1;
    default: return 0;
    }
}


struct demon_Message_table { uint8_t unused__; };

static inline size_t demon_Message_vec_len(demon_Message_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_Message_table_t demon_Message_vec_at(demon_Message_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_Message_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_Message)

__flatbuffers_define_union_field(flatbuffers_, 1, demon_Message, events, demon_Event, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* DEMON_READER_H */
