#ifndef DEMON_VERIFIER_H
#define DEMON_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef DEMON_READER_H
#include "demon_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int demon_Inotify_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_TCPSocket_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_SurveillanceEvent_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_RunCommand_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_KillProcess_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_ProcessLaunched_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_ChildCreationError_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_ProcessTerminated_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_TCPSocketListening_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_InotifyPathUpdated_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_EstablishTCPConnection_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_EstablishUnixConnection_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_Message_verify_table(flatcc_table_verifier_descriptor_t *td);

static int demon_Surveillance_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, demon_Inotify_verify_table); /* Inotify */
    case 2: return flatcc_verify_union_table(ud, demon_TCPSocket_verify_table); /* TCPSocket */
    default: return flatcc_verify_ok;
    }
}

static int demon_Event_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, demon_RunCommand_verify_table); /* RunCommand */
    case 2: return flatcc_verify_union_table(ud, demon_KillProcess_verify_table); /* KillProcess */
    case 3: return flatcc_verify_union_table(ud, demon_EstablishTCPConnection_verify_table); /* EstablishTCPConnection */
    case 4: return flatcc_verify_union_table(ud, demon_EstablishUnixConnection_verify_table); /* EstablishUnixConnection */
    case 5: return flatcc_verify_union_table(ud, demon_ProcessLaunched_verify_table); /* ProcessLaunched */
    case 6: return flatcc_verify_union_table(ud, demon_ChildCreationError_verify_table); /* ChildCreationError */
    case 7: return flatcc_verify_union_table(ud, demon_ProcessTerminated_verify_table); /* ProcessTerminated */
    case 8: return flatcc_verify_union_table(ud, demon_TCPSocketListening_verify_table); /* TCPSocketListening */
    case 9: return flatcc_verify_union_table(ud, demon_InotifyPathUpdated_verify_table); /* InotifyPathUpdated */
    default: return flatcc_verify_ok;
    }
}

static int demon_Inotify_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* root_paths */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 1, 0, 1, 1, INT64_C(4294967295)) /* trigger_events */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* size */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_Inotify_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_Inotify_identifier, &demon_Inotify_verify_table);
}

static inline int demon_Inotify_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_Inotify_identifier, &demon_Inotify_verify_table);
}

static inline int demon_Inotify_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_Inotify_type_identifier, &demon_Inotify_verify_table);
}

static inline int demon_Inotify_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_Inotify_type_identifier, &demon_Inotify_verify_table);
}

static inline int demon_Inotify_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_Inotify_verify_table);
}

static inline int demon_Inotify_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_Inotify_verify_table);
}

static inline int demon_Inotify_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_Inotify_verify_table);
}

static inline int demon_Inotify_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_Inotify_verify_table);
}

static int demon_TCPSocket_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* destport */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_TCPSocket_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_TCPSocket_identifier, &demon_TCPSocket_verify_table);
}

static inline int demon_TCPSocket_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_TCPSocket_identifier, &demon_TCPSocket_verify_table);
}

static inline int demon_TCPSocket_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_TCPSocket_type_identifier, &demon_TCPSocket_verify_table);
}

static inline int demon_TCPSocket_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_TCPSocket_type_identifier, &demon_TCPSocket_verify_table);
}

static inline int demon_TCPSocket_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_TCPSocket_verify_table);
}

static inline int demon_TCPSocket_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_TCPSocket_verify_table);
}

static inline int demon_TCPSocket_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_TCPSocket_verify_table);
}

static inline int demon_TCPSocket_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_TCPSocket_verify_table);
}

static int demon_SurveillanceEvent_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_union_field(td, 1, 0, &demon_Surveillance_union_verifier) /* event */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_SurveillanceEvent_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_SurveillanceEvent_identifier, &demon_SurveillanceEvent_verify_table);
}

static inline int demon_SurveillanceEvent_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_SurveillanceEvent_identifier, &demon_SurveillanceEvent_verify_table);
}

static inline int demon_SurveillanceEvent_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_SurveillanceEvent_type_identifier, &demon_SurveillanceEvent_verify_table);
}

static inline int demon_SurveillanceEvent_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_SurveillanceEvent_type_identifier, &demon_SurveillanceEvent_verify_table);
}

static inline int demon_SurveillanceEvent_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_SurveillanceEvent_verify_table);
}

static inline int demon_SurveillanceEvent_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_SurveillanceEvent_verify_table);
}

static inline int demon_SurveillanceEvent_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_SurveillanceEvent_verify_table);
}

static inline int demon_SurveillanceEvent_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_SurveillanceEvent_verify_table);
}

static int demon_RunCommand_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* path */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 1, 0) /* args */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 2, 0) /* envp */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 4, 4) /* flags */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 4, 4) /* stack_size */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 5, 0, &demon_SurveillanceEvent_verify_table) /* to_watch */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_RunCommand_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_RunCommand_identifier, &demon_RunCommand_verify_table);
}

static inline int demon_RunCommand_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_RunCommand_identifier, &demon_RunCommand_verify_table);
}

static inline int demon_RunCommand_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_RunCommand_type_identifier, &demon_RunCommand_verify_table);
}

static inline int demon_RunCommand_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_RunCommand_type_identifier, &demon_RunCommand_verify_table);
}

static inline int demon_RunCommand_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_RunCommand_verify_table);
}

static inline int demon_RunCommand_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_RunCommand_verify_table);
}

static inline int demon_RunCommand_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_RunCommand_verify_table);
}

static inline int demon_RunCommand_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_RunCommand_verify_table);
}

static int demon_KillProcess_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* pid */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_KillProcess_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_KillProcess_identifier, &demon_KillProcess_verify_table);
}

static inline int demon_KillProcess_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_KillProcess_identifier, &demon_KillProcess_verify_table);
}

static inline int demon_KillProcess_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_KillProcess_type_identifier, &demon_KillProcess_verify_table);
}

static inline int demon_KillProcess_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_KillProcess_type_identifier, &demon_KillProcess_verify_table);
}

static inline int demon_KillProcess_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_KillProcess_verify_table);
}

static inline int demon_KillProcess_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_KillProcess_verify_table);
}

static inline int demon_KillProcess_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_KillProcess_verify_table);
}

static inline int demon_KillProcess_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_KillProcess_verify_table);
}

static int demon_ProcessLaunched_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* pid */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_ProcessLaunched_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_ProcessLaunched_identifier, &demon_ProcessLaunched_verify_table);
}

static inline int demon_ProcessLaunched_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_ProcessLaunched_identifier, &demon_ProcessLaunched_verify_table);
}

static inline int demon_ProcessLaunched_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_ProcessLaunched_type_identifier, &demon_ProcessLaunched_verify_table);
}

static inline int demon_ProcessLaunched_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_ProcessLaunched_type_identifier, &demon_ProcessLaunched_verify_table);
}

static inline int demon_ProcessLaunched_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_ProcessLaunched_verify_table);
}

static inline int demon_ProcessLaunched_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_ProcessLaunched_verify_table);
}

static inline int demon_ProcessLaunched_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_ProcessLaunched_verify_table);
}

static inline int demon_ProcessLaunched_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_ProcessLaunched_verify_table);
}

static int demon_ChildCreationError_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* errno */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_ChildCreationError_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_ChildCreationError_identifier, &demon_ChildCreationError_verify_table);
}

static inline int demon_ChildCreationError_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_ChildCreationError_identifier, &demon_ChildCreationError_verify_table);
}

static inline int demon_ChildCreationError_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_ChildCreationError_type_identifier, &demon_ChildCreationError_verify_table);
}

static inline int demon_ChildCreationError_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_ChildCreationError_type_identifier, &demon_ChildCreationError_verify_table);
}

static inline int demon_ChildCreationError_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_ChildCreationError_verify_table);
}

static inline int demon_ChildCreationError_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_ChildCreationError_verify_table);
}

static inline int demon_ChildCreationError_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_ChildCreationError_verify_table);
}

static inline int demon_ChildCreationError_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_ChildCreationError_verify_table);
}

static int demon_ProcessTerminated_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* pid */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* errno */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_ProcessTerminated_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_ProcessTerminated_identifier, &demon_ProcessTerminated_verify_table);
}

static inline int demon_ProcessTerminated_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_ProcessTerminated_identifier, &demon_ProcessTerminated_verify_table);
}

static inline int demon_ProcessTerminated_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_ProcessTerminated_type_identifier, &demon_ProcessTerminated_verify_table);
}

static inline int demon_ProcessTerminated_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_ProcessTerminated_type_identifier, &demon_ProcessTerminated_verify_table);
}

static inline int demon_ProcessTerminated_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_ProcessTerminated_verify_table);
}

static inline int demon_ProcessTerminated_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_ProcessTerminated_verify_table);
}

static inline int demon_ProcessTerminated_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_ProcessTerminated_verify_table);
}

static inline int demon_ProcessTerminated_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_ProcessTerminated_verify_table);
}

static int demon_TCPSocketListening_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* port */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_TCPSocketListening_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_TCPSocketListening_identifier, &demon_TCPSocketListening_verify_table);
}

static inline int demon_TCPSocketListening_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_TCPSocketListening_identifier, &demon_TCPSocketListening_verify_table);
}

static inline int demon_TCPSocketListening_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_TCPSocketListening_type_identifier, &demon_TCPSocketListening_verify_table);
}

static inline int demon_TCPSocketListening_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_TCPSocketListening_type_identifier, &demon_TCPSocketListening_verify_table);
}

static inline int demon_TCPSocketListening_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_TCPSocketListening_verify_table);
}

static inline int demon_TCPSocketListening_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_TCPSocketListening_verify_table);
}

static inline int demon_TCPSocketListening_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_TCPSocketListening_verify_table);
}

static inline int demon_TCPSocketListening_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_TCPSocketListening_verify_table);
}

static int demon_InotifyPathUpdated_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* path */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 1, 0, 1, 1, INT64_C(4294967295)) /* trigger_events */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* size */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_InotifyPathUpdated_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_InotifyPathUpdated_identifier, &demon_InotifyPathUpdated_verify_table);
}

static inline int demon_InotifyPathUpdated_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_InotifyPathUpdated_identifier, &demon_InotifyPathUpdated_verify_table);
}

static inline int demon_InotifyPathUpdated_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_InotifyPathUpdated_type_identifier, &demon_InotifyPathUpdated_verify_table);
}

static inline int demon_InotifyPathUpdated_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_InotifyPathUpdated_type_identifier, &demon_InotifyPathUpdated_verify_table);
}

static inline int demon_InotifyPathUpdated_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_InotifyPathUpdated_verify_table);
}

static inline int demon_InotifyPathUpdated_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_InotifyPathUpdated_verify_table);
}

static inline int demon_InotifyPathUpdated_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_InotifyPathUpdated_verify_table);
}

static inline int demon_InotifyPathUpdated_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_InotifyPathUpdated_verify_table);
}

static int demon_EstablishTCPConnection_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* destport */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_EstablishTCPConnection_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_EstablishTCPConnection_identifier, &demon_EstablishTCPConnection_verify_table);
}

static inline int demon_EstablishTCPConnection_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_EstablishTCPConnection_identifier, &demon_EstablishTCPConnection_verify_table);
}

static inline int demon_EstablishTCPConnection_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_EstablishTCPConnection_type_identifier, &demon_EstablishTCPConnection_verify_table);
}

static inline int demon_EstablishTCPConnection_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_EstablishTCPConnection_type_identifier, &demon_EstablishTCPConnection_verify_table);
}

static inline int demon_EstablishTCPConnection_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_EstablishTCPConnection_verify_table);
}

static inline int demon_EstablishTCPConnection_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_EstablishTCPConnection_verify_table);
}

static inline int demon_EstablishTCPConnection_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_EstablishTCPConnection_verify_table);
}

static inline int demon_EstablishTCPConnection_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_EstablishTCPConnection_verify_table);
}

static int demon_EstablishUnixConnection_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* path */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_EstablishUnixConnection_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_EstablishUnixConnection_identifier, &demon_EstablishUnixConnection_verify_table);
}

static inline int demon_EstablishUnixConnection_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_EstablishUnixConnection_identifier, &demon_EstablishUnixConnection_verify_table);
}

static inline int demon_EstablishUnixConnection_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_EstablishUnixConnection_type_identifier, &demon_EstablishUnixConnection_verify_table);
}

static inline int demon_EstablishUnixConnection_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_EstablishUnixConnection_type_identifier, &demon_EstablishUnixConnection_verify_table);
}

static inline int demon_EstablishUnixConnection_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_EstablishUnixConnection_verify_table);
}

static inline int demon_EstablishUnixConnection_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_EstablishUnixConnection_verify_table);
}

static inline int demon_EstablishUnixConnection_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_EstablishUnixConnection_verify_table);
}

static inline int demon_EstablishUnixConnection_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_EstablishUnixConnection_verify_table);
}

static int demon_Message_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_union_field(td, 1, 0, &demon_Event_union_verifier) /* events */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_Message_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_Message_identifier, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_Message_identifier, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_Message_type_identifier, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_Message_type_identifier, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_Message_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* DEMON_VERIFIER_H */
