// automatically generated by the FlatBuffers compiler, do not modify


// @generated

use core::mem;
use core::cmp::Ordering;

extern crate flatbuffers;
use self::flatbuffers::{EndianScalar, Follow};

#[allow(unused_imports, dead_code)]
pub mod erreurs {

  use core::mem;
  use core::cmp::Ordering;

  extern crate flatbuffers;
  use self::flatbuffers::{EndianScalar, Follow};

pub enum ErreurOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Erreur<'a> {
  pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for Erreur<'a> {
  type Inner = Erreur<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: flatbuffers::Table::new(buf, loc) }
  }
}

impl<'a> Erreur<'a> {
  pub const VT_CODE: flatbuffers::VOffsetT = 4;
  pub const VT_CONTEXTE: flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
    Erreur { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
    _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
    args: &'args ErreurArgs<'args>
  ) -> flatbuffers::WIPOffset<Erreur<'bldr>> {
    let mut builder = ErreurBuilder::new(_fbb);
    if let Some(x) = args.contexte { builder.add_contexte(x); }
    builder.add_code(args.code);
    builder.finish()
  }


  #[inline]
  pub fn code(&self) -> i16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i16>(Erreur::VT_CODE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn contexte(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<flatbuffers::ForwardsUOffset<&str>>(Erreur::VT_CONTEXTE, None)}
  }
}

impl flatbuffers::Verifiable for Erreur<'_> {
  #[inline]
  fn run_verifier(
    v: &mut flatbuffers::Verifier, pos: usize
  ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
    use self::flatbuffers::Verifiable;
    v.visit_table(pos)?
     .visit_field::<i16>("code", Self::VT_CODE, false)?
     .visit_field::<flatbuffers::ForwardsUOffset<&str>>("contexte", Self::VT_CONTEXTE, false)?
     .finish();
    Ok(())
  }
}
pub struct ErreurArgs<'a> {
    pub code: i16,
    pub contexte: Option<flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ErreurArgs<'a> {
  #[inline]
  fn default() -> Self {
    ErreurArgs {
      code: 0,
      contexte: None,
    }
  }
}

pub struct ErreurBuilder<'a: 'b, 'b> {
  fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
  start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b> ErreurBuilder<'a, 'b> {
  #[inline]
  pub fn add_code(&mut self, code: i16) {
    self.fbb_.push_slot::<i16>(Erreur::VT_CODE, code, 0);
  }
  #[inline]
  pub fn add_contexte(&mut self, contexte: flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(Erreur::VT_CONTEXTE, contexte);
  }
  #[inline]
  pub fn new(_fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>) -> ErreurBuilder<'a, 'b> {
    let start = _fbb.start_table();
    ErreurBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> flatbuffers::WIPOffset<Erreur<'a>> {
    let o = self.fbb_.end_table(self.start_);
    flatbuffers::WIPOffset::new(o.value())
  }
}

impl core::fmt::Debug for Erreur<'_> {
  fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
    let mut ds = f.debug_struct("Erreur");
      ds.field("code", &self.code());
      ds.field("contexte", &self.contexte());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Erreur`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_erreur_unchecked`.
pub fn root_as_erreur(buf: &[u8]) -> Result<Erreur, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root::<Erreur>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Erreur` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_erreur_unchecked`.
pub fn size_prefixed_root_as_erreur(buf: &[u8]) -> Result<Erreur, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root::<Erreur>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Erreur` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_erreur_unchecked`.
pub fn root_as_erreur_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Erreur<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::root_with_opts::<Erreur<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Erreur` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_erreur_unchecked`.
pub fn size_prefixed_root_as_erreur_with_opts<'b, 'o>(
  opts: &'o flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Erreur<'b>, flatbuffers::InvalidFlatbuffer> {
  flatbuffers::size_prefixed_root_with_opts::<Erreur<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Erreur and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Erreur`.
pub unsafe fn root_as_erreur_unchecked(buf: &[u8]) -> Erreur {
  flatbuffers::root_unchecked::<Erreur>(buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Erreur and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Erreur`.
pub unsafe fn size_prefixed_root_as_erreur_unchecked(buf: &[u8]) -> Erreur {
  flatbuffers::size_prefixed_root_unchecked::<Erreur>(buf)
}
#[inline]
pub fn finish_erreur_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<Erreur<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_erreur_buffer<'a, 'b>(fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>, root: flatbuffers::WIPOffset<Erreur<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod erreurs

