# automatically generated by the FlatBuffers compiler, do not modify

# namespace: demon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ChildCreationError(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ChildCreationError()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChildCreationError(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ChildCreationError
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChildCreationError
    def ErrorCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ChildCreationErrorStart(builder):
    builder.StartObject(1)

def Start(builder):
    ChildCreationErrorStart(builder)

def ChildCreationErrorAddErrorCode(builder, errorCode):
    builder.PrependUint32Slot(0, errorCode, 0)

def AddErrorCode(builder, errorCode):
    ChildCreationErrorAddErrorCode(builder, errorCode)

def ChildCreationErrorEnd(builder):
    return builder.EndObject()

def End(builder):
    return ChildCreationErrorEnd(builder)
