# automatically generated by the FlatBuffers compiler, do not modify

# namespace: demon

#
# Main message table
#
class Event(object):
    NONE = 0
    RunCommand = 1
    KillProcess = 2
    EstablishTCPConnection = 3
    EstablishUnixConnection = 4
    ProcessLaunched = 5
    ChildCreationError = 6
    ProcessTerminated = 7
    TCPSocketListening = 8
    InotifyPathUpdated = 9
