# automatically generated by the FlatBuffers compiler, do not modify

# namespace: demon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InotifyWatchListUpdated(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InotifyWatchListUpdated()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInotifyWatchListUpdated(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InotifyWatchListUpdated
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InotifyWatchListUpdated
    def Path(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def InotifyWatchListUpdatedStart(builder):
    builder.StartObject(1)

def Start(builder):
    InotifyWatchListUpdatedStart(builder)

def InotifyWatchListUpdatedAddPath(builder, path):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)

def AddPath(builder, path):
    InotifyWatchListUpdatedAddPath(builder, path)

def InotifyWatchListUpdatedEnd(builder):
    return builder.EndObject()

def End(builder):
    return InotifyWatchListUpdatedEnd(builder)
