# automatically generated by the FlatBuffers compiler, do not modify

# namespace: demon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TCPSocketListening(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TCPSocketListening()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTCPSocketListening(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TCPSocketListening
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TCPSocketListening
    def Port(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def TCPSocketListeningStart(builder):
    builder.StartObject(1)

def Start(builder):
    TCPSocketListeningStart(builder)

def TCPSocketListeningAddPort(builder, port):
    builder.PrependUint16Slot(0, port, 0)

def AddPort(builder, port):
    TCPSocketListeningAddPort(builder, port)

def TCPSocketListeningEnd(builder):
    return builder.EndObject()

def End(builder):
    return TCPSocketListeningEnd(builder)
