# automatically generated by the FlatBuffers compiler, do not modify

# namespace: demon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EstablishUnixConnection(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EstablishUnixConnection()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEstablishUnixConnection(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EstablishUnixConnection
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EstablishUnixConnection
    def Path(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EstablishUnixConnectionStart(builder):
    builder.StartObject(1)

def Start(builder):
    EstablishUnixConnectionStart(builder)

def EstablishUnixConnectionAddPath(builder, path):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(path), 0)

def AddPath(builder, path):
    EstablishUnixConnectionAddPath(builder, path)

def EstablishUnixConnectionEnd(builder):
    return builder.EndObject()

def End(builder):
    return EstablishUnixConnectionEnd(builder)
