# automatically generated by the FlatBuffers compiler, do not modify

# namespace: demon

#
# Main message table
#
class Event(object):
    NONE = 0
    RunCommand = 1
    KillProcess = 2
    EstablishTCPConnection = 3
    EstablishUnixConnection = 4
    ExecveTerminated = 5
    ProcessLaunched = 6
    ChildCreationError = 7
    ProcessTerminated = 8
    TCPSocketListening = 9
    InotifyPathUpdated = 10
    InotifyWatchListUpdated = 11
    SocketWatched = 12
    SocketWatchTerminated = 13
