# automatically generated by the FlatBuffers compiler, do not modify

# namespace: demon

class InotifyEvent(object):
    modified = 0
    created = 1
    size_reached = 2
    deleted = 3
    accessed = 4
