# automatically generated by the FlatBuffers compiler, do not modify

# namespace: demon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class KillProcess(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = KillProcess()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsKillProcess(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # KillProcess
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # KillProcess
    def Pid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def KillProcessStart(builder):
    builder.StartObject(1)

def Start(builder):
    KillProcessStart(builder)

def KillProcessAddPid(builder, pid):
    builder.PrependInt32Slot(0, pid, 0)

def AddPid(builder, pid):
    KillProcessAddPid(builder, pid)

def KillProcessEnd(builder):
    return builder.EndObject()

def End(builder):
    return KillProcessEnd(builder)
