# automatically generated by the FlatBuffers compiler, do not modify

# namespace: demon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ProcessTerminated(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ProcessTerminated()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProcessTerminated(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ProcessTerminated
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ProcessTerminated
    def Pid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # ProcessTerminated
    def ErrorCode(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ProcessTerminatedStart(builder):
    builder.StartObject(2)

def Start(builder):
    ProcessTerminatedStart(builder)

def ProcessTerminatedAddPid(builder, pid):
    builder.PrependInt32Slot(0, pid, 0)

def AddPid(builder, pid):
    ProcessTerminatedAddPid(builder, pid)

def ProcessTerminatedAddErrorCode(builder, errorCode):
    builder.PrependUint32Slot(1, errorCode, 0)

def AddErrorCode(builder, errorCode):
    ProcessTerminatedAddErrorCode(builder, errorCode)

def ProcessTerminatedEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProcessTerminatedEnd(builder)
