# automatically generated by the FlatBuffers compiler, do not modify

# namespace: demon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SocketWatched(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SocketWatched()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSocketWatched(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SocketWatched
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SocketWatched
    def Port(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def SocketWatchedStart(builder):
    builder.StartObject(1)

def Start(builder):
    SocketWatchedStart(builder)

def SocketWatchedAddPort(builder, port):
    builder.PrependInt32Slot(0, port, 0)

def AddPort(builder, port):
    SocketWatchedAddPort(builder, port)

def SocketWatchedEnd(builder):
    return builder.EndObject()

def End(builder):
    return SocketWatchedEnd(builder)
