# automatically generated by the FlatBuffers compiler, do not modify

# namespace: demon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SurveillanceEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SurveillanceEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSurveillanceEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SurveillanceEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SurveillanceEvent
    def EventType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SurveillanceEvent
    def Event(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def SurveillanceEventStart(builder):
    builder.StartObject(2)

def Start(builder):
    SurveillanceEventStart(builder)

def SurveillanceEventAddEventType(builder, eventType):
    builder.PrependUint8Slot(0, eventType, 0)

def AddEventType(builder, eventType):
    SurveillanceEventAddEventType(builder, eventType)

def SurveillanceEventAddEvent(builder, event):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(event), 0)

def AddEvent(builder, event):
    SurveillanceEventAddEvent(builder, event)

def SurveillanceEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return SurveillanceEventEnd(builder)
