#ifndef DEMON_VERIFIER_H
#define DEMON_VERIFIER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef DEMON_READER_H
#include "demon_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int demon_Command_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_InotifyEvent_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_CloneEvent_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_WatchSocketEvent_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_ChildErrorEvent_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_CloneErrorEvent_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_FileCreationEvent_verify_table(flatcc_table_verifier_descriptor_t *td);
static int demon_Message_verify_table(flatcc_table_verifier_descriptor_t *td);

static int demon_Event_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, demon_InotifyEvent_verify_table); /* InotifyEvent */
    case 2: return flatcc_verify_union_table(ud, demon_CloneEvent_verify_table); /* CloneEvent */
    case 3: return flatcc_verify_union_table(ud, demon_WatchSocketEvent_verify_table); /* WatchSocketEvent */
    case 4: return flatcc_verify_union_table(ud, demon_ChildErrorEvent_verify_table); /* ChildErrorEvent */
    case 5: return flatcc_verify_union_table(ud, demon_CloneErrorEvent_verify_table); /* CloneErrorEvent */
    case 6: return flatcc_verify_union_table(ud, demon_FileCreationEvent_verify_table); /* FileCreationEvent */
    default: return flatcc_verify_ok;
    }
}

static int demon_Command_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* command_name */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* arg1 */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* arg2 */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* arg3 */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 1, 1) /* type */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_Command_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_Command_identifier, &demon_Command_verify_table);
}

static inline int demon_Command_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_Command_identifier, &demon_Command_verify_table);
}

static inline int demon_Command_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_Command_type_identifier, &demon_Command_verify_table);
}

static inline int demon_Command_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_Command_type_identifier, &demon_Command_verify_table);
}

static inline int demon_Command_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_Command_verify_table);
}

static inline int demon_Command_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_Command_verify_table);
}

static inline int demon_Command_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_Command_verify_table);
}

static inline int demon_Command_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_Command_verify_table);
}

static int demon_InotifyEvent_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* pathname */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* flags */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* size_target */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_InotifyEvent_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_InotifyEvent_identifier, &demon_InotifyEvent_verify_table);
}

static inline int demon_InotifyEvent_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_InotifyEvent_identifier, &demon_InotifyEvent_verify_table);
}

static inline int demon_InotifyEvent_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_InotifyEvent_type_identifier, &demon_InotifyEvent_verify_table);
}

static inline int demon_InotifyEvent_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_InotifyEvent_type_identifier, &demon_InotifyEvent_verify_table);
}

static inline int demon_InotifyEvent_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_InotifyEvent_verify_table);
}

static inline int demon_InotifyEvent_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_InotifyEvent_verify_table);
}

static inline int demon_InotifyEvent_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_InotifyEvent_verify_table);
}

static inline int demon_InotifyEvent_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_InotifyEvent_verify_table);
}

static int demon_CloneEvent_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* stack_size */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* pathname */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* flags */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* args */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 4, 0) /* envp */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 4, 4) /* group_id */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_CloneEvent_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_CloneEvent_identifier, &demon_CloneEvent_verify_table);
}

static inline int demon_CloneEvent_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_CloneEvent_identifier, &demon_CloneEvent_verify_table);
}

static inline int demon_CloneEvent_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_CloneEvent_type_identifier, &demon_CloneEvent_verify_table);
}

static inline int demon_CloneEvent_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_CloneEvent_type_identifier, &demon_CloneEvent_verify_table);
}

static inline int demon_CloneEvent_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_CloneEvent_verify_table);
}

static inline int demon_CloneEvent_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_CloneEvent_verify_table);
}

static inline int demon_CloneEvent_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_CloneEvent_verify_table);
}

static inline int demon_CloneEvent_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_CloneEvent_verify_table);
}

static int demon_WatchSocketEvent_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    return flatcc_verify_ok;
}

static inline int demon_WatchSocketEvent_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_WatchSocketEvent_identifier, &demon_WatchSocketEvent_verify_table);
}

static inline int demon_WatchSocketEvent_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_WatchSocketEvent_identifier, &demon_WatchSocketEvent_verify_table);
}

static inline int demon_WatchSocketEvent_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_WatchSocketEvent_type_identifier, &demon_WatchSocketEvent_verify_table);
}

static inline int demon_WatchSocketEvent_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_WatchSocketEvent_type_identifier, &demon_WatchSocketEvent_verify_table);
}

static inline int demon_WatchSocketEvent_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_WatchSocketEvent_verify_table);
}

static inline int demon_WatchSocketEvent_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_WatchSocketEvent_verify_table);
}

static inline int demon_WatchSocketEvent_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_WatchSocketEvent_verify_table);
}

static inline int demon_WatchSocketEvent_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_WatchSocketEvent_verify_table);
}

static int demon_ChildErrorEvent_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* pid */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 1, 0, &demon_Command_verify_table) /* command */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* group_id */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_ChildErrorEvent_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_ChildErrorEvent_identifier, &demon_ChildErrorEvent_verify_table);
}

static inline int demon_ChildErrorEvent_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_ChildErrorEvent_identifier, &demon_ChildErrorEvent_verify_table);
}

static inline int demon_ChildErrorEvent_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_ChildErrorEvent_type_identifier, &demon_ChildErrorEvent_verify_table);
}

static inline int demon_ChildErrorEvent_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_ChildErrorEvent_type_identifier, &demon_ChildErrorEvent_verify_table);
}

static inline int demon_ChildErrorEvent_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_ChildErrorEvent_verify_table);
}

static inline int demon_ChildErrorEvent_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_ChildErrorEvent_verify_table);
}

static inline int demon_ChildErrorEvent_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_ChildErrorEvent_verify_table);
}

static inline int demon_ChildErrorEvent_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_ChildErrorEvent_verify_table);
}

static int demon_CloneErrorEvent_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    return flatcc_verify_ok;
}

static inline int demon_CloneErrorEvent_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_CloneErrorEvent_identifier, &demon_CloneErrorEvent_verify_table);
}

static inline int demon_CloneErrorEvent_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_CloneErrorEvent_identifier, &demon_CloneErrorEvent_verify_table);
}

static inline int demon_CloneErrorEvent_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_CloneErrorEvent_type_identifier, &demon_CloneErrorEvent_verify_table);
}

static inline int demon_CloneErrorEvent_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_CloneErrorEvent_type_identifier, &demon_CloneErrorEvent_verify_table);
}

static inline int demon_CloneErrorEvent_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_CloneErrorEvent_verify_table);
}

static inline int demon_CloneErrorEvent_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_CloneErrorEvent_verify_table);
}

static inline int demon_CloneErrorEvent_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_CloneErrorEvent_verify_table);
}

static inline int demon_CloneErrorEvent_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_CloneErrorEvent_verify_table);
}

static int demon_FileCreationEvent_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* filepath */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* group_id */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* pid */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_FileCreationEvent_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_FileCreationEvent_identifier, &demon_FileCreationEvent_verify_table);
}

static inline int demon_FileCreationEvent_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_FileCreationEvent_identifier, &demon_FileCreationEvent_verify_table);
}

static inline int demon_FileCreationEvent_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_FileCreationEvent_type_identifier, &demon_FileCreationEvent_verify_table);
}

static inline int demon_FileCreationEvent_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_FileCreationEvent_type_identifier, &demon_FileCreationEvent_verify_table);
}

static inline int demon_FileCreationEvent_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_FileCreationEvent_verify_table);
}

static inline int demon_FileCreationEvent_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_FileCreationEvent_verify_table);
}

static inline int demon_FileCreationEvent_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_FileCreationEvent_verify_table);
}

static inline int demon_FileCreationEvent_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_FileCreationEvent_verify_table);
}

static int demon_Message_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* code */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 2, 0, &demon_Event_union_verifier) /* events */)) return ret;
    return flatcc_verify_ok;
}

static inline int demon_Message_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_Message_identifier, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_Message_identifier, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, demon_Message_type_identifier, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_typed_root_with_size(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, demon_Message_type_identifier, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_root_with_identifier_and_size(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root_with_size(buf, bufsiz, fid, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &demon_Message_verify_table);
}

static inline int demon_Message_verify_as_root_with_type_hash_and_size(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root_with_size(buf, bufsiz, thash, &demon_Message_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* DEMON_VERIFIER_H */
