#ifndef DEMON_READER_H
#define DEMON_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct demon_Command_table *demon_Command_table_t;
typedef struct demon_Command_table *demon_Command_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_Command_vec_t;
typedef flatbuffers_uoffset_t *demon_Command_mutable_vec_t;
typedef const struct demon_InotifyEvent_table *demon_InotifyEvent_table_t;
typedef struct demon_InotifyEvent_table *demon_InotifyEvent_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_InotifyEvent_vec_t;
typedef flatbuffers_uoffset_t *demon_InotifyEvent_mutable_vec_t;
typedef const struct demon_CloneEvent_table *demon_CloneEvent_table_t;
typedef struct demon_CloneEvent_table *demon_CloneEvent_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_CloneEvent_vec_t;
typedef flatbuffers_uoffset_t *demon_CloneEvent_mutable_vec_t;
typedef const struct demon_WatchSocketEvent_table *demon_WatchSocketEvent_table_t;
typedef struct demon_WatchSocketEvent_table *demon_WatchSocketEvent_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_WatchSocketEvent_vec_t;
typedef flatbuffers_uoffset_t *demon_WatchSocketEvent_mutable_vec_t;
typedef const struct demon_ChildErrorEvent_table *demon_ChildErrorEvent_table_t;
typedef struct demon_ChildErrorEvent_table *demon_ChildErrorEvent_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_ChildErrorEvent_vec_t;
typedef flatbuffers_uoffset_t *demon_ChildErrorEvent_mutable_vec_t;
typedef const struct demon_CloneErrorEvent_table *demon_CloneErrorEvent_table_t;
typedef struct demon_CloneErrorEvent_table *demon_CloneErrorEvent_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_CloneErrorEvent_vec_t;
typedef flatbuffers_uoffset_t *demon_CloneErrorEvent_mutable_vec_t;
typedef const struct demon_FileCreationEvent_table *demon_FileCreationEvent_table_t;
typedef struct demon_FileCreationEvent_table *demon_FileCreationEvent_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_FileCreationEvent_vec_t;
typedef flatbuffers_uoffset_t *demon_FileCreationEvent_mutable_vec_t;
typedef const struct demon_Message_table *demon_Message_table_t;
typedef struct demon_Message_table *demon_Message_mutable_table_t;
typedef const flatbuffers_uoffset_t *demon_Message_vec_t;
typedef flatbuffers_uoffset_t *demon_Message_mutable_vec_t;
#ifndef demon_Command_file_identifier
#define demon_Command_file_identifier 0
#endif
/* deprecated, use demon_Command_file_identifier */
#ifndef demon_Command_identifier
#define demon_Command_identifier 0
#endif
#define demon_Command_type_hash ((flatbuffers_thash_t)0x4987ccd3)
#define demon_Command_type_identifier "\xd3\xcc\x87\x49"
#ifndef demon_Command_file_extension
#define demon_Command_file_extension "bin"
#endif
#ifndef demon_InotifyEvent_file_identifier
#define demon_InotifyEvent_file_identifier 0
#endif
/* deprecated, use demon_InotifyEvent_file_identifier */
#ifndef demon_InotifyEvent_identifier
#define demon_InotifyEvent_identifier 0
#endif
#define demon_InotifyEvent_type_hash ((flatbuffers_thash_t)0xc91a1770)
#define demon_InotifyEvent_type_identifier "\x70\x17\x1a\xc9"
#ifndef demon_InotifyEvent_file_extension
#define demon_InotifyEvent_file_extension "bin"
#endif
#ifndef demon_CloneEvent_file_identifier
#define demon_CloneEvent_file_identifier 0
#endif
/* deprecated, use demon_CloneEvent_file_identifier */
#ifndef demon_CloneEvent_identifier
#define demon_CloneEvent_identifier 0
#endif
#define demon_CloneEvent_type_hash ((flatbuffers_thash_t)0x1594b95)
#define demon_CloneEvent_type_identifier "\x95\x4b\x59\x01"
#ifndef demon_CloneEvent_file_extension
#define demon_CloneEvent_file_extension "bin"
#endif
#ifndef demon_WatchSocketEvent_file_identifier
#define demon_WatchSocketEvent_file_identifier 0
#endif
/* deprecated, use demon_WatchSocketEvent_file_identifier */
#ifndef demon_WatchSocketEvent_identifier
#define demon_WatchSocketEvent_identifier 0
#endif
#define demon_WatchSocketEvent_type_hash ((flatbuffers_thash_t)0xbc74a0c0)
#define demon_WatchSocketEvent_type_identifier "\xc0\xa0\x74\xbc"
#ifndef demon_WatchSocketEvent_file_extension
#define demon_WatchSocketEvent_file_extension "bin"
#endif
#ifndef demon_ChildErrorEvent_file_identifier
#define demon_ChildErrorEvent_file_identifier 0
#endif
/* deprecated, use demon_ChildErrorEvent_file_identifier */
#ifndef demon_ChildErrorEvent_identifier
#define demon_ChildErrorEvent_identifier 0
#endif
#define demon_ChildErrorEvent_type_hash ((flatbuffers_thash_t)0x8b5fdd0a)
#define demon_ChildErrorEvent_type_identifier "\x0a\xdd\x5f\x8b"
#ifndef demon_ChildErrorEvent_file_extension
#define demon_ChildErrorEvent_file_extension "bin"
#endif
#ifndef demon_CloneErrorEvent_file_identifier
#define demon_CloneErrorEvent_file_identifier 0
#endif
/* deprecated, use demon_CloneErrorEvent_file_identifier */
#ifndef demon_CloneErrorEvent_identifier
#define demon_CloneErrorEvent_identifier 0
#endif
#define demon_CloneErrorEvent_type_hash ((flatbuffers_thash_t)0x2fea24a5)
#define demon_CloneErrorEvent_type_identifier "\xa5\x24\xea\x2f"
#ifndef demon_CloneErrorEvent_file_extension
#define demon_CloneErrorEvent_file_extension "bin"
#endif
#ifndef demon_FileCreationEvent_file_identifier
#define demon_FileCreationEvent_file_identifier 0
#endif
/* deprecated, use demon_FileCreationEvent_file_identifier */
#ifndef demon_FileCreationEvent_identifier
#define demon_FileCreationEvent_identifier 0
#endif
#define demon_FileCreationEvent_type_hash ((flatbuffers_thash_t)0xde273507)
#define demon_FileCreationEvent_type_identifier "\x07\x35\x27\xde"
#ifndef demon_FileCreationEvent_file_extension
#define demon_FileCreationEvent_file_extension "bin"
#endif
#ifndef demon_Message_file_identifier
#define demon_Message_file_identifier 0
#endif
/* deprecated, use demon_Message_file_identifier */
#ifndef demon_Message_identifier
#define demon_Message_identifier 0
#endif
#define demon_Message_type_hash ((flatbuffers_thash_t)0x5a6e7ab9)
#define demon_Message_type_identifier "\xb9\x7a\x6e\x5a"
#ifndef demon_Message_file_extension
#define demon_Message_file_extension "bin"
#endif

typedef int8_t demon_NetworkEventType_enum_t;
__flatbuffers_define_integer_type(demon_NetworkEventType, demon_NetworkEventType_enum_t, 8)
#define demon_NetworkEventType_INOTIFY ((demon_NetworkEventType_enum_t)INT8_C(0))
#define demon_NetworkEventType_CLONE ((demon_NetworkEventType_enum_t)INT8_C(1))
#define demon_NetworkEventType_WATCH_SOCKET ((demon_NetworkEventType_enum_t)INT8_C(2))

static inline const char *demon_NetworkEventType_name(demon_NetworkEventType_enum_t value)
{
    switch (value) {
    case demon_NetworkEventType_INOTIFY: return "INOTIFY";
    case demon_NetworkEventType_CLONE: return "CLONE";
    case demon_NetworkEventType_WATCH_SOCKET: return "WATCH_SOCKET";
    default: return "";
    }
}

static inline int demon_NetworkEventType_is_known_value(demon_NetworkEventType_enum_t value)
{
    switch (value) {
    case demon_NetworkEventType_INOTIFY: return 1;
    case demon_NetworkEventType_CLONE: return 1;
    case demon_NetworkEventType_WATCH_SOCKET: return 1;
    default: return 0;
    }
}



struct demon_Command_table { uint8_t unused__; };

static inline size_t demon_Command_vec_len(demon_Command_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_Command_table_t demon_Command_vec_at(demon_Command_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_Command_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_Command)

__flatbuffers_define_string_field(0, demon_Command, command_name, 0)
__flatbuffers_define_string_field(1, demon_Command, arg1, 0)
__flatbuffers_define_string_field(2, demon_Command, arg2, 0)
__flatbuffers_define_string_field(3, demon_Command, arg3, 0)
__flatbuffers_define_scalar_field(4, demon_Command, type, demon_NetworkEventType, demon_NetworkEventType_enum_t, INT8_C(0))

struct demon_InotifyEvent_table { uint8_t unused__; };

static inline size_t demon_InotifyEvent_vec_len(demon_InotifyEvent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_InotifyEvent_table_t demon_InotifyEvent_vec_at(demon_InotifyEvent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_InotifyEvent_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_InotifyEvent)

__flatbuffers_define_string_field(0, demon_InotifyEvent, pathname, 0)
__flatbuffers_define_scalar_field(1, demon_InotifyEvent, flags, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(2, demon_InotifyEvent, size_target, flatbuffers_int32, int32_t, INT32_C(0))

struct demon_CloneEvent_table { uint8_t unused__; };

static inline size_t demon_CloneEvent_vec_len(demon_CloneEvent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_CloneEvent_table_t demon_CloneEvent_vec_at(demon_CloneEvent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_CloneEvent_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_CloneEvent)

__flatbuffers_define_scalar_field(0, demon_CloneEvent, stack_size, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_string_field(1, demon_CloneEvent, pathname, 0)
__flatbuffers_define_scalar_field(2, demon_CloneEvent, flags, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_string_field(3, demon_CloneEvent, args, 0)
__flatbuffers_define_string_field(4, demon_CloneEvent, envp, 0)
__flatbuffers_define_scalar_field(5, demon_CloneEvent, group_id, flatbuffers_int32, int32_t, INT32_C(0))

struct demon_WatchSocketEvent_table { uint8_t unused__; };

static inline size_t demon_WatchSocketEvent_vec_len(demon_WatchSocketEvent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_WatchSocketEvent_table_t demon_WatchSocketEvent_vec_at(demon_WatchSocketEvent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_WatchSocketEvent_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_WatchSocketEvent)


struct demon_ChildErrorEvent_table { uint8_t unused__; };

static inline size_t demon_ChildErrorEvent_vec_len(demon_ChildErrorEvent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_ChildErrorEvent_table_t demon_ChildErrorEvent_vec_at(demon_ChildErrorEvent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_ChildErrorEvent_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_ChildErrorEvent)

__flatbuffers_define_scalar_field(0, demon_ChildErrorEvent, pid, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_vector_field(1, demon_ChildErrorEvent, command, demon_Command_vec_t, 0)
__flatbuffers_define_scalar_field(2, demon_ChildErrorEvent, group_id, flatbuffers_int32, int32_t, INT32_C(0))

struct demon_CloneErrorEvent_table { uint8_t unused__; };

static inline size_t demon_CloneErrorEvent_vec_len(demon_CloneErrorEvent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_CloneErrorEvent_table_t demon_CloneErrorEvent_vec_at(demon_CloneErrorEvent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_CloneErrorEvent_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_CloneErrorEvent)


struct demon_FileCreationEvent_table { uint8_t unused__; };

static inline size_t demon_FileCreationEvent_vec_len(demon_FileCreationEvent_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_FileCreationEvent_table_t demon_FileCreationEvent_vec_at(demon_FileCreationEvent_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_FileCreationEvent_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_FileCreationEvent)

__flatbuffers_define_string_field(0, demon_FileCreationEvent, filepath, 0)
__flatbuffers_define_scalar_field(1, demon_FileCreationEvent, group_id, flatbuffers_int32, int32_t, INT32_C(0))
__flatbuffers_define_scalar_field(2, demon_FileCreationEvent, pid, flatbuffers_int32, int32_t, INT32_C(0))
/** 
 * Main message table
 *  */
typedef uint8_t demon_Event_union_type_t;
__flatbuffers_define_integer_type(demon_Event, demon_Event_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, demon_Event)
#define demon_Event_NONE ((demon_Event_union_type_t)UINT8_C(0))
#define demon_Event_InotifyEvent ((demon_Event_union_type_t)UINT8_C(1))
#define demon_Event_CloneEvent ((demon_Event_union_type_t)UINT8_C(2))
#define demon_Event_WatchSocketEvent ((demon_Event_union_type_t)UINT8_C(3))
#define demon_Event_ChildErrorEvent ((demon_Event_union_type_t)UINT8_C(4))
#define demon_Event_CloneErrorEvent ((demon_Event_union_type_t)UINT8_C(5))
#define demon_Event_FileCreationEvent ((demon_Event_union_type_t)UINT8_C(6))

static inline const char *demon_Event_type_name(demon_Event_union_type_t type)
{
    switch (type) {
    case demon_Event_NONE: return "NONE";
    case demon_Event_InotifyEvent: return "InotifyEvent";
    case demon_Event_CloneEvent: return "CloneEvent";
    case demon_Event_WatchSocketEvent: return "WatchSocketEvent";
    case demon_Event_ChildErrorEvent: return "ChildErrorEvent";
    case demon_Event_CloneErrorEvent: return "CloneErrorEvent";
    case demon_Event_FileCreationEvent: return "FileCreationEvent";
    default: return "";
    }
}

static inline int demon_Event_is_known_type(demon_Event_union_type_t type)
{
    switch (type) {
    case demon_Event_NONE: return 1;
    case demon_Event_InotifyEvent: return 1;
    case demon_Event_CloneEvent: return 1;
    case demon_Event_WatchSocketEvent: return 1;
    case demon_Event_ChildErrorEvent: return 1;
    case demon_Event_CloneErrorEvent: return 1;
    case demon_Event_FileCreationEvent: return 1;
    default: return 0;
    }
}


struct demon_Message_table { uint8_t unused__; };

static inline size_t demon_Message_vec_len(demon_Message_vec_t vec)
__flatbuffers_vec_len(vec)
static inline demon_Message_table_t demon_Message_vec_at(demon_Message_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(demon_Message_table_t, vec, i, 0)
__flatbuffers_table_as_root(demon_Message)

__flatbuffers_define_scalar_field(0, demon_Message, code, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_union_field(flatbuffers_, 2, demon_Message, events, demon_Event, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* DEMON_READER_H */
