#ifndef ERREUR_BUILDER_H
#define ERREUR_BUILDER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef ERREUR_READER_H
#include "erreur_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

static const flatbuffers_voffset_t __erreurs_Erreur_required[] = { 0 };
typedef flatbuffers_ref_t erreurs_Erreur_ref_t;
static erreurs_Erreur_ref_t erreurs_Erreur_clone(flatbuffers_builder_t *B, erreurs_Erreur_table_t t);
__flatbuffers_build_table(flatbuffers_, erreurs_Erreur, 2)

#define __erreurs_Erreur_formal_args , uint64_t v0, flatbuffers_string_ref_t v1
#define __erreurs_Erreur_call_args , v0, v1
static inline erreurs_Erreur_ref_t erreurs_Erreur_create(flatbuffers_builder_t *B __erreurs_Erreur_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, erreurs_Erreur, erreurs_Erreur_file_identifier, erreurs_Erreur_type_identifier)

__flatbuffers_build_scalar_field(0, flatbuffers_, erreurs_Erreur_code, flatbuffers_uint64, uint64_t, 8, 8, UINT64_C(0), erreurs_Erreur)
__flatbuffers_build_string_field(1, flatbuffers_, erreurs_Erreur_contexte, erreurs_Erreur)

static inline erreurs_Erreur_ref_t erreurs_Erreur_create(flatbuffers_builder_t *B __erreurs_Erreur_formal_args)
{
    if (erreurs_Erreur_start(B)
        || erreurs_Erreur_code_add(B, v0)
        || erreurs_Erreur_contexte_add(B, v1)) {
        return 0;
    }
    return erreurs_Erreur_end(B);
}

static erreurs_Erreur_ref_t erreurs_Erreur_clone(flatbuffers_builder_t *B, erreurs_Erreur_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (erreurs_Erreur_start(B)
        || erreurs_Erreur_code_pick(B, t)
        || erreurs_Erreur_contexte_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, erreurs_Erreur_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* ERREUR_BUILDER_H */
