#ifndef ERREUR_READER_H
#define ERREUR_READER_H

/* Generated by flatcc 0.6.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif


typedef const struct erreurs_Erreur_table *erreurs_Erreur_table_t;
typedef struct erreurs_Erreur_table *erreurs_Erreur_mutable_table_t;
typedef const flatbuffers_uoffset_t *erreurs_Erreur_vec_t;
typedef flatbuffers_uoffset_t *erreurs_Erreur_mutable_vec_t;
#ifndef erreurs_Erreur_file_identifier
#define erreurs_Erreur_file_identifier 0
#endif
/* deprecated, use erreurs_Erreur_file_identifier */
#ifndef erreurs_Erreur_identifier
#define erreurs_Erreur_identifier 0
#endif
#define erreurs_Erreur_type_hash ((flatbuffers_thash_t)0xc9153600)
#define erreurs_Erreur_type_identifier "\x00\x36\x15\xc9"
#ifndef erreurs_Erreur_file_extension
#define erreurs_Erreur_file_extension "bin"
#endif



struct erreurs_Erreur_table { uint8_t unused__; };

static inline size_t erreurs_Erreur_vec_len(erreurs_Erreur_vec_t vec)
__flatbuffers_vec_len(vec)
static inline erreurs_Erreur_table_t erreurs_Erreur_vec_at(erreurs_Erreur_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(erreurs_Erreur_table_t, vec, i, 0)
__flatbuffers_table_as_root(erreurs_Erreur)

__flatbuffers_define_scalar_field(0, erreurs_Erreur, code, flatbuffers_uint64, uint64_t, UINT64_C(0))
__flatbuffers_define_string_field(1, erreurs_Erreur, contexte, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* ERREUR_READER_H */
