[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
daemonize = "0.5"
tokio = { version = "1", features = ["full"] }
nix = { version = "0.29", features = ["signal", "process", "fs"] }

[[bin]]
name = "clone"
path = "src/monitoring_tools/clone.rs"

[[bin]]
name = "foo"
path = "src/monitoring_tools/foo.rs"

[[bin]]
name = "test_clone"
path = "src/monitoring_tools/test_clone.rs"
